[package]
name = "mutools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.7.0"
rodio = "0.14.0"
tdpsola = "0.1.0"
byteorder = "1"
